import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "ExitoOooO Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        theme: dark,
      }}
    >
      <html lang="en" className="dark">
        <body className="min-h-screen  font-serif  relative flex flex-col">
          <header className="w-full z-20    ">
            <NavBar />
          </header>
          {children}
          <footer className="z-30">
            <Footer />
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
